### ISSUE TITLE
Convert frame in % or px

### ISSUE THREAD

**Issue by ametthey** [LottieFiles/lottie-interactivity#12]
I'm trying to make a scrolling event with a lottie interactivity object in a container  within another container. for that I need to "know" the lottie animation height, meaning is there a way to convert the frame in % or px ? 

Thanks a lot :)

**Comment by wallythewebdev** [comment]
I have a similar issue / question to this. 

I would like to have a lottie animation scrub through its frames based on how much of the lottie animation is visible in the container, not the view port. is this possible: 

Here is a visual representation: 

![Screenshot 2023-01-17 at 10 00 36](https://user-images.githubusercontent.com/28821463/212868165-15430750-489a-4933-86a0-a6d48125d127.png)

![Screenshot 2023-01-17 at 10 02 52](https://user-images.githubusercontent.com/28821463/212868732-4b28fac6-99fd-41ef-b045-c3c350ba0722.png)

![Screenshot 2023-01-17 at 10 04 22](https://user-images.githubusercontent.com/28821463/212869269-9e1e1bd8-b37c-4473-8820-bbb84c350e36.png)

Is there any way to do this or a possibility to do this?

**Comment by samuelOsborne** [comment]
@wallythewebdev Is this what you're looking for?

https://lottiefiles.com/interactivity#second

**Comment by wallythewebdev** [comment]
@samuelOsborne - Thanks for the reply :) 

Not quite I don't think - only because, in the second example, the scroll animation is linked to how much of the container is visible in the view port. 

![Screenshot 2023-01-17 at 10 44 43](https://user-images.githubusercontent.com/28821463/212878929-4ace0710-8b28-46f6-9940-90e69d65d8e3.png)

![Screenshot 2023-01-17 at 10 46 43](https://user-images.githubusercontent.com/28821463/212879363-2751e01e-13d1-4293-99ca-1b994357cd20.png)

What I am trying to change (or hoping to change) is instead of Lottie interactivity targeting the view port to messure how much of an animation should be changed, is to target the lottie palyer instead. 

Why? 

well in some cases the container is very large i.e. 1500px for example, in this case the animation will run for much longer than intended and you will need to workout the the visibility of the element base on the container height: 

![Screenshot 2023-01-17 at 10 52 14](https://user-images.githubusercontent.com/28821463/212880790-ca3fdf89-02bd-46f1-b380-a761a9dffb79.png)

instead of 

![Screenshot 2023-01-17 at 10 56 09](https://user-images.githubusercontent.com/28821463/212881381-d62c15db-329a-4c89-bf38-bd47fc77ea9d.png)

I hope this makes sense but please let me know if there is anything not clear, thanks again for your reply :)
