### ISSUE TITLE
Animation won't work when the container is set to position sticky

### ISSUE THREAD

**Issue by maximebeguin** [LottieFiles/lottie-interactivity#20]
As the title mentioned, I'm not able to apply the animation of the lottie file on scroll when the container is set to position fixed or sticky.  While it works great on a "normal" container, as soon as the lottie file hits the sticky point, the animation will stop even if I continue to scroll. Any idea how to solve this?

**Comment by samuelOsborne** [comment]
Hi @maximebeguin 

With lottie-interactivity you can do a scroll effect relative to a container, so you can have a sticky element but use the container underneath. I've made a codepen to [show you](https://codepen.io/Osbro/pen/vYxqxjG)

Related documentation: https://github.com/LottieFiles/lottie-interactivity#scroll-effect-relative-to-container

Here I set the container to the id of my text, so when scrolling my animation plays relative to that rather than the player's position on the screen.

Let me know if that helps you out.

Cheers
