### ISSUE TITLE
Add a destroy() or refresh() so we can change the interactivity after it's been created

### ISSUE THREAD

**Issue by wplit** [LottieFiles/lottie-interactivity#40]
## Overview

There doesn't seem to be a way to create a new instance with new interactivity settings once they've already been applied. It would be great to have a refresh or destroy so new interactions can be added to existing.

Use case; I'm trying to add inside Vue app, need to be able to switch between scroll / click. Following the instructions on adding on mounted works great, but if I try to re-add on watch it causes issues. I think it will need to be destroyed before adding again.

**Comment by samuelOsborne** [comment]
Thanks @wplit for the suggestion! Will look in to implementing this :-)

**Comment by samuelOsborne** [comment]
Hi @wplit this has been implemented in the latest version of lottie-interactivity, the method to use is "redefineOptions" and can be called the same way you call the "create" method.

Usage example:

https://codepen.io/Osbro/pen/WNEYYQa

**Comment by wplit** [comment]
@samuelOsborne Ah amazing! Will try this straight away, thanks so much for adding it in.

**Comment by patratel** [comment]
Hello, following up on this , would it be possible to add a destroy event also? I need it in order to avoid errors when i remove element from the DOM in my Vue application

**Comment by samuelOsborne** [comment]
Hi @patratel, if you're removing the element from the DOM and using the lottie-player, you can listen to the 'destroyed' event: 

https://github.com/LottieFiles/lottie-player/blob/master/src/lottie-player.ts#L341

I say this because lottie-interactivity won't be aware that you've removed the player from the DOM, you should look in to the documentation of the player you're using to see which event you should listen too. Let me know which lottie player you're using and I'd be happy to help :-)

**Comment by samuelOsborne** [comment]
Closing this issue as the "redefineOptions" method has been implemented.
